### ISSUE TITLE
RHOB parsing

### ISSUE THREAD

**Issue by jessepisel** [jessepisel/summer_fellows#196]
RHOB mnemonic is aliased as density porosity. It should be aliased as bulk density, or density.
![image](https://user-images.githubusercontent.com/12752033/87704705-66953b80-c762-11ea-818a-4bc0cfb2955c.png)

Can you update this alias in the dictionary of aliases?

**Comment by jessepisel** [comment]
It looks like anything that has the description of `Bulk Density` is showing up as density porosity. This needs to be updated in the alias dictionary 
![image](https://user-images.githubusercontent.com/12752033/87705039-ea4f2800-c762-11ea-8d6f-d45fd08b1115.png)

**Comment by dingdonged** [comment]
I'm changing it

**Comment by dingdonged** [comment]
It's really weird that Craine's well book labelled bulk density as density porosity though

**Comment by jessepisel** [comment]
Interesting. Let's use bulk density instead of density porosity, this is one curve that people would want as just bulk density rather than lumped in with density porosity
